### ISSUE TITLE
run example failed!

### ISSUE THREAD

**Issue by andyyuan78** [andersbll/neural_artistic_style#32]
envy@ub1404:~/os_pri/github/neural_artistic_style$ python neural_artistic_style.py --subject images/tuebingen.jpg --style images/starry_night.jpg
CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "neural_artistic_style.py", line 138, in <module>
    run()
  File "neural_artistic_style.py", line 99, in run
    layers, pixel_mean = vgg_net(args.network, pool_method=args.pool_method)
  File "/home/envy/os_pri/github/neural_artistic_style/matconvnet.py", line 26, in vgg_net
    matconvnet = scipy.io.loadmat(path)
  File "/home/envy/.local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/home/envy/.local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "/home/envy/.local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "scipy/io/matlab/mio5_utils.pyx", line 668, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:7079)
  File "scipy/io/matlab/mio5_utils.pyx", line 714, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6471)
  File "scipy/io/matlab/mio5_utils.pyx", line 887, in scipy.io.matlab.mio5_utils.VarReader5.read_cells (scipy/io/matlab/mio5_utils.c:8967)
  File "scipy/io/matlab/mio5_utils.pyx", line 666, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy/io/matlab/mio5_utils.c:5976)
  File "scipy/io/matlab/mio5_utils.pyx", line 716, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6501)
  File "scipy/io/matlab/mio5_utils.pyx", line 965, in scipy.io.matlab.mio5_utils.VarReader5.read_struct (scipy/io/matlab/mio5_utils.c:9937)
  File "scipy/io/matlab/mio5_utils.pyx", line 666, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy/io/matlab/mio5_utils.c:5976)
  File "scipy/io/matlab/mio5_utils.pyx", line 714, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6471)
  File "scipy/io/matlab/mio5_utils.pyx", line 887, in scipy.io.matlab.mio5_utils.VarReader5.read_cells (scipy/io/matlab/mio5_utils.c:8967)
  File "scipy/io/matlab/mio5_utils.pyx", line 666, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy/io/matlab/mio5_utils.c:5976)
  File "scipy/io/matlab/mio5_utils.pyx", line 698, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6196)
  File "scipy/io/matlab/mio5_utils.pyx", line 771, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex (scipy/io/matlab/mio5_utils.c:7541)
  File "scipy/io/matlab/mio5_utils.pyx", line 444, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric (scipy/io/matlab/mio5_utils.c:4242)
  File "scipy/io/matlab/mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element (scipy/io/matlab/mio5_utils.c:3892)
  File "scipy/io/matlab/streams.pyx", line 193, in scipy.io.matlab.streams.ZlibInputStream.read_string (scipy/io/matlab/streams.c:2925)
  File "scipy/io/matlab/streams.pyx", line 169, in scipy.io.matlab.streams.ZlibInputStream.read_into (scipy/io/matlab/streams.c:2711)
  File "scipy/io/matlab/streams.pyx", line 156, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer (scipy/io/matlab/streams.c:2583)
zlib.error: Error -3 while decompressing: invalid stored block lengths
envy@ub1404:~/os_pri/github/neural_artistic_style$

**Comment by andersbll** [comment]
I have never seen that before. Maybe there is an error in the VGG net you have downloaded. Could you verify that the MD5 checksum matches the one given on http://www.vlfeat.org/matconvnet/pretrained/ ?

**Comment by andyyuan78** [comment]
yes, the md5sum doesn't match.
