### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by ClaireCJS** [andersbll/neural_artistic_style#33]
It just won't start on windows. Perhaps because I don't know where to put the "cuda" folder, since the installation doesn't say how to add that part to the rest?

S:\new\DeepStyle\neural_artistic_style-master>neural_artistic_style.py --subject image.jpg --style s
tyle.jpg --output output.jpg
CUDArray: CUDA back-end not available, using NumPy.

At that point, I get a windows error:

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: python.exe
  Application Version:  0.0.0.0
  Application Timestamp:    56abcaee
  Fault Module Name:    ntdll.dll
  Fault Module Version: 6.1.7601.19160
  Fault Module Timestamp:   56bcd74c
  Exception Code:   c0000005
  Exception Offset: 000000000004a604
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: 3935
  Additional Information 2: 39350178b1f7dc4d15d5471cf2a5a09f
  Additional Information 3: 6976
  Additional Information 4: 697614677dd37f475b8d30bce4aa474e

Seems like perhaps an exception is nto being caught?

**Comment by ClaireCJS** [comment]
As an update, I got things this far, but am still stuck (I am ATI/AMD so NumPy is fine, I don't care about speed, I just want to get this working):

CUDArray: Failed to load CUDA back-end.
Traceback (most recent call last):
  File "neural_artistic_style.py", line 7, in <module>
    import deeppy as dp
  File "build\bdist.win-amd64\egg\deeppy__init__.py", line 1, in <module>
  File "build\bdist.win-amd64\egg\deeppy\dataset__init__.py", line 2, in <module>
  File "build\bdist.win-amd64\egg\deeppy\dataset\infimnist.py", line 6, in <module>
  File "build\bdist.win-amd64\egg\deeppy\base.py", line 1, in <module>
  File "C:\anaconda\lib\site-packages\cudarray-0.1.dev0-py2.7-win-amd64.egg\cudarray__init__.py", li
ne 20, in <module>
    from .cudarray import *
  File "C:\anaconda\lib\site-packages\cudarray-0.1.dev0-py2.7-win-amd64.egg\cudarray\cudarray.py", li
ne 2, in <module>
    from .wrap.array_data import ArrayData
ImportError: No module named array_data

What am I doing wrong? Definitely something!

**Comment by FabienLavocat** [comment]
Can you try to make sure the backend is set to Numpy and not Cuda. The error message says that it's trying to load the Cuda libraries
http://andersbll.github.io/deeppy-website/installation-guide.html

**Comment by ClaireCJS** [comment]
Thanks! I'm not quite sure how to do that, but if I unset CUDARRAY_BACKEND, my test fails completely - windows error, no console output at all.  Same thing if i set it to numpy.  If I set it to cuda, I get the error message from my comment above (ArrayData import fail).

**Comment by ClaireCJS** [comment]
The result of "import cudarray; print(cudarray._backend)" is "numpy".

**Comment by FabienLavocat** [comment]
Did you run that command to install Cudarray?
python setup.py --without-cuda install

**Comment by ClaireCJS** [comment]
I'm running it again!

**Comment by ClaireCJS** [comment]
(Because I've tried the CUDA install a few different times now.)

Anyway, that setup did not create any setup error messages.  But I still get an error when I try to generate an image. And I'm possibly making things worse by trying to fix this in various ways and not remembering which things I might have undone.  I think I've spent 4 hrs.

Where I'm at now:

verify-backend.py:
import cudarray
print(cudarray._backend)

output:
CUDArray: Failed to load CUDA back-end.
Traceback (most recent call last):
  File "verify-cuda-backend.py", line 1, in <module>
    import cudarray
  File "C:\anaconda\lib\site-packages\cudarray-0.1.dev0-py2.7-win-amd64.egg\cudarray__init__.py", li
ne 20, in <module>
    from .cudarray import *
  File "C:\anaconda\lib\site-packages\cudarray-0.1.dev0-py2.7-win-amd64.egg\cudarray\cudarray.py", li
ne 2, in <module>
    from .wrap.array_data import ArrayData
ImportError: No module named array_data

**Comment by ClaireCJS** [comment]
What strikes me as interesting about my situation:

1) Cudarray would not even build unless I ran setup.py with the "--without-cuda install "

2) neural_artistic_style.py _ONLY_ runs (produces console output) if I set the environment variable CUDAARRAY_BACKEND=cuda ... Everything else is a full on windows exception.

How weird that 1= "no cuda" and 2="cuda". This does not seem right. But it's the only combination that's even given me output to even get the error message about ArrayData.

And for the life of me, I can't google or find anything about ArrayDatay in conda.exe or anywhere.

**Comment by FabienLavocat** [comment]
I've faced a lot of installation issues on Ubuntu (I'm a big Windows guy...) but in the end I made it work. It took me a while too.
On the very first error, do you have more logs? Maybe in the Event Viewer?
Did you install Python 64bits?

**Comment by ClaireCJS** [comment]
I have a hard time with things like these, even though I'm a command-line
guy, because I live in my own proprietary world, haha.  Windows+TakeCommand
for 20+ yrs + Cygwin.

I _think_ this might have been the error:

Faulting application name: python.exe, version: 0.0.0.0, time stamp:
0x56abcaee
Faulting module name: ntdll.dll, version: 6.1.7601.19160, time stamp:
0x56bcd74c
Exception code: 0xc0000005
Fault offset: 0x000000000004a604
Faulting process id: 0x5010
Faulting application start time: 0x01d180d7154c6a4b
Faulting application path: C:\anaconda\python.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 53ca1384-ecca-11e5-a8a3-001167c2c87c

and when I reproduced it, this is what popped up:

Problem signature:
  Problem Event Name: APPCRASH
  Application Name: python.exe
  Application Version: 0.0.0.0
  Application Timestamp: 56abcaee
  Fault Module Name: ntdll.dll
  Fault Module Version: 6.1.7601.19160
  Fault Module Timestamp: 56bcd74c
  Exception Code: c0000005
  Exception Offset: 000000000004a604
  OS Version: 6.1.7601.2.1.0.256.1
  Locale ID: 1033
  Additional Information 1: 3935
  Additional Information 2: 39350178b1f7dc4d15d5471cf2a5a09f
  Additional Information 3: 6976
  Additional Information 4: 697614677dd37f475b8d30bce4aa474e

Thanks :)

**Comment by ClaireCJS** [comment]
but anyway, the error that i'd actually like to try to fix is this one:

ImportError: No module named array_data

...Because that's the situation where DeepStyle is the closest to running -- it actually produces STDOUT at least :)

**Comment by ClaireCJS** [comment]
I'd let you remote into my machine, too, if it would help.  That might be a nightmare though.  It seems like the error is simply that some module called array_data is not being loaded. It's weird because I can't find reference to array_data anywhere.

I really wanted to start running this on permutated sets of images...
