### ISSUE TITLE
problems with runinig on osx 

### ISSUE THREAD

**Issue by ctrlok** [andersbll/neural_artistic_style#37]
``` bash
python neural_artistic_style.py --subject /tmp/1.jpg --style /tmp/2.jpg

Traceback (most recent call last):
  File "neural_artistic_style.py", line 138, in <module>
    run()
  File "neural_artistic_style.py", line 99, in run
    layers, pixel_mean = vgg_net(args.network, pool_method=args.pool_method)
  File "/Users/me/neural_artistic_style/matconvnet.py", line 27, in vgg_net
    img_mean = matconvnet['meta'][0][0][1][0][0][0][0][0]
KeyError: 'meta'
```

**Comment by andersbll** [comment]
Hi, what is the md5sum of the VGG net you have downloaded?

**Comment by ctrlok** [comment]
MD5 (./imagenet-vgg-verydeep-19.mat) = 8ee3263992981a1d26e73b3ca028a123

I add

``` python
    for key, value in matconvnet.iteritems() :
        print key
```

and recive 

``` bash
layers
__header__
__globals__
classes
__version__
normalization
```

So, you think that is problem in file?

**Comment by andersbll** [comment]
According to http://www.vlfeat.org/matconvnet/pretrained/ it should be 49e623de543b207d57fab0f6eaf79a7e. Try downloading it again. :)

**Comment by ctrlok** [comment]
Thanks. Looks like I have an old one.
