### ISSUE TITLE
CUDArray: CUDA back-end not available, using NumPy.

### ISSUE THREAD

**Issue by sukerlove** [andersbll/neural_artistic_style#46]
Dear andersbll:
I run command, but it's not work

gtx1080@suker:~/work/src/github.com/andersbll/neural_artistic_style$ python neural_artistic_style.py --subject images/tuebingen.jpg --style images/starry_night.jpg
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/gtx1080/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "neural_artistic_style.py", line 138, in <module>
    run()
  File "neural_artistic_style.py", line 99, in run
    layers, pixel_mean = vgg_net(args.network, pool_method=args.pool_method)
  File "/home/gtx1080/work/src/github.com/andersbll/neural_artistic_style/matconvnet.py", line 27, in vgg_net
    img_mean = matconvnet['meta'][0][0][1][0][0][0][0][0]
KeyError: 'meta'
gtx1080@suker:~/work/src/github.com/andersbll/neural_artistic_style$ 

Machine configuration:
OS............: ubuntu14.04
Memory........: 32G
CPU...........: Intel Core i7-6700K 4.00GHz*8
DisplayCard...: NVIDIA GeForce GTX 1080
Harddisk......: 256G ssd

---

gtx1080@suker:~$ nvidia-smi 
Tue Aug 23 21:17:24 2016  
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.35                 Driver Version: 367.35                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
| 34%   35C    P8    10W / 200W |   1306MiB /  8112MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1169    G   /usr/bin/X                                    1014MiB |
|    0      2025    G   compiz                                          59MiB |
|    0      3571    G   unity-control-center                             2MiB |
|    0     10412    G   ...ves-passed-by-fd --v8-snapshot-passed-by-   227MiB |
+-----------------------------------------------------------------------------+
gtx1080@suker:~$ 

I am looking forward to your reply.
Thanks.

**Comment by DylanAlloy** [comment]
It's way too hard to get CUDA working. Every time I follow the instructions, and every time I have to deal with this error. I also have the same graphics card, the 1080. 

Lots of other software has no issues finding my CUDA installation and I even went out of my way each time to add seemingly unnecessary environment variables.

My bashrc now looks like this:

export PATH=$PATH:/usr/local/cuda-8.0/bin:/usr/local/android-studio/bin/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64
export CPATH=$CPATH:/usr/local/cuda-8.0/include
export CUDNN_ENABLED=1
export CUDA_PREFIX=$CUDA_PREFIX:/usr/local/cuda-8.0

and yet I have no results for all that clutter. 

Also the dependencies in the README are in opposite order. You need CudArray before you need Deeppy so you'll always run into one failed installation before you get everything up to date unless you can remember to flip the order of the instructions.
