### ISSUE TITLE
Can not load model

### ISSUE THREAD

**Issue by SkyCrawl** [andersbll/neural_artistic_style#51]
Hello @andersbll 

thank you for your program and I look forward using it. However, I can not get it to run at the moment. Would you, perhaps, have an idea what could be wrong? 

If I try with `imagenet-vgg-verydeep-19.mat`:

``` shell
python neural_artistic_style.py --subject content.jpg --style style.jpg --iterations 500 --network imagenet-vgg-verydeep-19.mat
Traceback (most recent call last):
  File "neural_artistic_style.py", line 138, in <module>
    run()
  File "neural_artistic_style.py", line 102, in run
    style_img = imread(args.style) - pixel_mean
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```

If I try with another model:

``` shell
python neural_artistic_style.py --subject content.jpg --style style.jpg --iterations 500 --network googlenet-dag.mat
Traceback (most recent call last):
  File "neural_artistic_style.py", line 138, in <module>
    run()
  File "neural_artistic_style.py", line 99, in run
    layers, pixel_mean = vgg_net(args.network, pool_method=args.pool_method)
  File "./matconvnet.py", line 47, in vgg_net
    raise ValueError('invalid layer type: %s' % layer_type)
ValueError: invalid layer type: o
```

The second error seems to be simple (the model is just not supported) but the first one should not happen in my opinion if the installation is correct. I didn't notice anything out of the ordinary when I installed though :(.

**Comment by andersbll** [comment]
Hey thanks for the error report! It seems that MatConvnet has changed the structure in their `.mat` file. I have changed the network loader accordingly.

**Comment by SkyCrawl** [comment]
Thank you @andersbll but I have another problem now:

```shell
$ python neural_artistic_style.py --subject margrethe.jpg --style donelli.jpg --random-seed 597635419 --iterations 500 --learn-rate 2.0 --smoothness 5e-08 --network matconvnet-vgg-verydeep-16.mat

Traceback (most recent call last):
  File "neural_artistic_style.py", line 138, in <module>
    run()
  File "neural_artistic_style.py", line 99, in run
    layers, pixel_mean = vgg_net(args.network, pool_method=args.pool_method)
  File "/Users/SkyCrawl/Shared/_git/neu-art-style/matconvnet.py", line 27, in vgg_net
    img_mean = matconvnet['meta'][0][0][2][0][0][2]
IndexError: invalid index (2)
```

Perhaps another format change?
