### ISSUE TITLE
You application require Matlab?

### ISSUE THREAD

**Issue by vit1251** [andersbll/neural_artistic_style#6]
``` bash
CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "./neural_artistic_style.py", line 112, in <module>
    run()
  File "./neural_artistic_style.py", line 77, in run
    layers, img_mean = vgg19_net(args.vgg19, pool_method='avg')
  File "C:\WORK\py\netral\neural_artistic_style\matconvnet.py", line 34, in vgg19_net
    matconvnet = scipy.io.loadmat(path)
  File "C:\Python27\lib\site-packages\scipy\io\matlab\mio.py", line 134, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "C:\Python27\lib\site-packages\scipy\io\matlab\mio.py", line 57, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "C:\Python27\lib\site-packages\scipy\io\matlab\mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 2] No such file or directory: 'imagenet-vgg-verydeep-19.mat'
```

It mean that I must have Matlab some source code?

**Comment by vit1251** [comment]
Answer: just require download this file not Matlab require.

**Comment by streamgao** [comment]
I have the same issue

**Comment by andersbll** [comment]
You need to download the pretrained VGG network. See the requirements in the README.
